var h=(t,e,r)=>{if(!e.has(t))throw TypeError("Cannot "+r)};var a=(t,e,r)=>(h(t,e,"read from private field"),r?r.call(t):e.get(t)),l=(t,e,r)=>{if(e.has(t))throw TypeError("Cannot add the same private member more than once");e instanceof WeakSet?e.add(t):e.set(t,r)},p=(t,e,r,n)=>(h(t,e,"write to private field"),n?n.call(t,r):e.set(t,r),r);import{S as P,i as g}from"./assets/vendor-5b791d57.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))n(o);new MutationObserver(o=>{for(const s of o)if(s.type==="childList")for(const m of s.addedNodes)m.tagName==="LINK"&&m.rel==="modulepreload"&&n(m)}).observe(document,{childList:!0,subtree:!0});function r(o){const s={};return o.integrity&&(s.integrity=o.integrity),o.referrerPolicy&&(s.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?s.credentials="include":o.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(o){if(o.ep)return;o.ep=!0;const s=r(o);fetch(o.href,s)}})();const $="28194821-49041d995ecd04735d9e20d11",I="https://pixabay.com/api/";var c,u,i;class v{constructor(){l(this,c,1);l(this,u,20);l(this,i,"")}async getPhotos(e){const r=`${I}?key=${$}&q=${a(this,i)}&page=${a(this,c)}&per_page=${a(this,u)}`;return await(await fetch(r)).json()}get query(){return a(this,i)}set query(e){p(this,i,e)}incrementPage(){p(this,c,a(this,c)+1)}}c=new WeakMap,u=new WeakMap,i=new WeakMap;const y=new P(".gallery a",{scaleImageToRatio:!0,captionsData:"alt",captionPosition:"bottom",captionDelay:250});function w(t){if(t.length===0){iziToast.show({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!"});return}t.forEach(e=>{const r=`
            <div class="card">
                <a href="${e.webformatURL}">
                    <img src="${e.webformatURL}" alt="${e.tags}">
                </a>
                <p>Likes: ${e.likes}</p>
                <p>Views: ${e.views}</p>
                <p>Comments: ${e.comments}</p>
                <p>Downloads: ${e.downloads}</p>
            </div>
        `;gallery.insertAdjacentHTML("beforeend",r),gallery.lastElementChild.querySelector("img").addEventListener("click",()=>{y.open({items:[{src:e.largeImageURL,title:e.tags}]})})}),y.refresh()}const q=document.getElementById("searchForm"),T=document.getElementById("searchInput"),E=document.getElementById("loader"),O=document.getElementById("gallery"),d=new v;let f;function L(){setTimeout(()=>{E.style.display="none"},750)}q.addEventListener("submit",async function(t){if(t.preventDefault(),f=T.value.trim(),f===""){g.show({title:"Error",message:"Please enter a search term.",backgroundColor:"orange"});return}E.style.display="block",O.innerHTML="",d.query=f;try{L();let e=await d.getPhotos();w(e.hits)}catch(e){b(e)}});function b(t){g.show({title:"Error",message:"An error occurred. Please try again later.",backgroundColor:"red"}),console.error("Error:",t)}window.addEventListener("scroll",A);async function A(){if(window.innerHeight+window.scrollY>=document.body.offsetHeight)try{L();let t=await d.getPhotos();d.incrementPage(),w(t.hits)}catch(t){b(t)}}
//# sourceMappingURL=commonHelpers.js.map
